Models.Knots = {
    name:"Knots",
    tileSize: 10,
    tiles: [
        {
            index: 0,
            image: "knots/corner.png",
            rotation: 0
        }, {
            index: 1,
            image: "knots/corner.png",
            rotation: 1
        }, {
            index: 2,
            image: "knots/corner.png",
            rotation: 2
        }, {
            index: 3,
            image: "knots/corner.png",
            rotation: 3
        }, {
            index: 4,
            image: "knots/line.png",
            rotation: 1
        }, {
            index: 5,
            image: "knots/line.png",
            rotation: 0
        }
    ],
    connections: [
        {
            /* Origin: 0 */
            left: 0,
            right: 2,
            weight: 1
        }, {
            left: 0,
            right: 3,
            weight: 1
        }, {
            bottom: 0,
            top: 1,
            weight: 1
        }, {
            bottom: 0,
            top: 2,
            weight: 1
        }, {
            left: 0,
            right: 4,
            weight: 1
        }, {
            bottom: 0,
            top: 5,
            weight: 1
        }, {
            /* Origin: 1 */
            left: 1,
            right: 2,
            weight: 1
        }, {
            left: 1,
            right: 3,
            weight: 1
        }, {
            bottom: 1,
            top: 0,
            weight: 1
        }, {
            bottom: 1,
            top: 3,
            weight: 1
        }, {
            left: 1,
            right: 4,
            weight: 1
        }, {
            bottom: 1,
            top: 4,
            weight: 1
        }, {
            /* Origin: 2 */
            left: 2,
            right: 0,
            weight: 1
        }, {
            left: 2,
            right: 1,
            weight: 1
        }, {
            bottom: 2,
            top: 0,
            weight: 1
        }, {
            bottom: 2,
            top: 3,
            weight: 1
        }, {
            bottom: 2,
            top: 4,
            weight: 1
        }, {
            left: 2,
            right: 5,
            weight: 1
        }, {
            /* Origin: 3 */
            left: 3,
            right: 0,
            weight: 1
        }, {
            left: 3,
            right: 1,
            weight: 1
        }, {
            bottom: 3,
            top: 1,
            weight: 1
        }, {
            bottom: 3,
            top: 2,
            weight: 1
        }, {
            bottom: 3,
            top: 5,
            weight: 1
        }, {
            left: 3,
            right: 5,
            weight: 1
        }, {
            /* Origin: 4 */
            left: 4,
            right: 4,
            weight: 1
        }, {
            left: 4,
            right: 2,
            weight: 1
        }, {
            left: 4,
            right: 3,
            weight: 1
        }, {
            bottom: 4,
            top: 0,
            weight: 1
        }, {
            bottom: 4,
            top: 3,
            weight: 1
        }, {
            /* Origin: 5 */
            bottom: 5,
            top: 5,
            weight: 1
        }, {
            bottom: 5,
            top: 1,
            weight: 1
        }, {
            bottom: 5,
            top: 2,
            weight: 1
        }, {
            left: 5,
            right: 0,
            weight: 1
        }, {
            left: 5,
            right: 1,
            weight: 1
        }
    ]
};